
var errno = {
    SUCCESS : 0,
    NOT_MODIFIED: 100,

    // error
    API_USER_NOT_LOGIN: 511,
    API_CREATE_USER_FAIL: 512,
    API_INVALID_PHONE: 513,
    API_INVALID_API_FORMAT: 515,
    API_USER_NO_EXIST: 520,
    API_USER_SIGNED: 521,
    API_INVALID_REGISTER_PHONE: 522,
    API_INVALID_PHONE_FORMAT: 523,
    API_INVALID_PASSWORD: 524,
    API_INVALID_METHOD: 525,
    API_SEND_AUTH_CODE_FAIL: 526,
    API_TOKEN_MISMATCH: 527,
    API_FILE_NOT_EXIST: 528, 
    API_INVALID_REGISTER_CODE: 529,
    API_SAME_PASSWORD_NOT_MODIFY : 530,
    API_REMOVE_FRIEND_ERR : 531,
    
    
    // connect server error
    CONN_USER_NOT_VERIFIED: 601,
    CONN_INVALID_GAME: 602,
    CONN_INVALID_APP: 603,
    CONN_USER_OFFLINE: 604,
    
    // group
    API_NOT_GROUP_OWNER : 701,
    API_NOT_HAVE_GROUP  : 702,
    API_NOT_GROUP_MEMBER: 703,
    API_SAME_OWNER_NOT_MODIFY : 704,
    API_MEMBERS_NOT_ENOUGH : 707,
    API_IS_GROUP_OWNER : 708,
    API_NO_DATA: 800,

    // friend
    FRIEND_USER_NOT_FOUND: 851,
    FRIEND_NO_INVITE_MSG: 852,
    FRIEND_IS_NOT_FRIEND: 853,
    FRIEND_SEARCH_USER_FAILED: 854,
    FRIEND_EXIST_IN_FRIENDS: 855, 
    FRIEND_NOT_QUEST_ADD_YOU: 856,
    
    API_DATA_IS_NULL: 901,       
    API_DATA_TYPE_WRONG: 902,
    API_DATA_OUT_OF_RANGE: 903,
    API_DATA_IS_NOT_ARRAY: 904,
    
    // redis error
    REDIS_GET_FAIL : 2001,
    REDIS_SET_FAIL : 2002,
    REDIS_INC_FAIL : 2003,
    REDIS_DEL_FAIL : 2004,
    REDIS_MULTI_FAIL : 2004,
    
        // mysql error
    MYSQL_FIND_FAIL : 1501,
    MYSQL_UPDATE_FAIL : 1502,
    MYSQL_SAVE_FAIL : 1503,
    MYSQL_USER_NOT_FOUND: 1504,
    MYSQL_INSERT_FAIL: 1505,

    ERR_NULL_ID: 9999
};

module.exports = errno;
